### PR TITLE
Update the readme to mention helptags so help docs actually load.

### PR DESCRIPTION
**Pull request by gravyboat**

### CODE REVIEW

**Comment by gravyboat** [comment]
@tpope Are you still merging in changes to vim-pathogen or is it no longer supported?

**Comment by tpope** [comment]
`Helptags` should be called at installation time, not startup time. I deliberately omitted it from `pathogen#infect()` for that reason.

**Comment by gravyboat** [comment]
When you say installation time do you mean installation of a plugin? Or installation of vim-pathogen? I'd just like to make it clearer as it took a visit to Stackoverflow to figure out why the Helptags weren't being loaded correctly. I see the notes here:

```
Normally to generate documentation, Vim expects you to run :helptags on each directory with documentation (e.g., :helptags ~/.vim/doc). Provided with pathogen.vim is a :Helptags command that does this on every directory in your 'runtimepath'. If you really want to get crazy, you could even invoke Helptags in your vimrc. I don't like to get crazy.
```

**Comment by tpope** [comment]
After each plugin installation. Ideally whatever you use to install Vim plugins would generate help tags automatically, but since `git clone` is the de facto install tool I provide `:Helptags` to ease that pain a bit.  I could see adding a FAQ entry for this.

**Comment by gravyboat** [comment]
Does `:Helptags` load the help docs permanently?

**Comment by tpope** [comment]
If you upgrade a plugin you will need to rerun `:Helptags` to get full coverage for any doc changes.

**Pull request closed without merging**
